language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
branches:
  only:
    - master
    - develop
install:
  - npm install
before_script:
  - npm run lint
  - npm run lint:test
  - npm test
script:
  - npm run build
after_success:
  - npm run test:coveralls
